version: '3.8'

services:
  auth-service:
    container_name: auth-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      # Node
      NODE_ENV: development
      PORT: 3001
      HOST: 0.0.0.0
      
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres123
      DB_DATABASE: auth_db
      DB_SYNCHRONIZE: false
      DB_LOGGING: true
      
      JWT_SECRET: your-super-secret-jwt-key-change-in-production-12345
      JWT_EXPIRES_IN: 7d
      JWT_REFRESH_SECRET: your-super-secret-refresh-key-change-in-production-67890
      JWT_REFRESH_EXPIRES_IN: 30d
      
      BCRYPT_SALT_ROUNDS: 10
      
      RABBITMQ_URL: amqp://rabbitmq:5672
      RABBITMQ_EXCHANGE: microservices_events
      RABBITMQ_QUEUE_AUTH: auth_queue
      
      ALLOWED_ORIGINS: http://localhost:3000,http://localhost:4200
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - microservices-network
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

  postgres:
    container_name: postgres-db
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: auth_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - microservices-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.13-management-alpine
    ports:
      - "5672:5672"   
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - microservices-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
  nginx:
    container_name: nginx-proxy
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth-service
    networks:
      - microservices-network
    restart: unless-stopped
volumes:
  postgres-data:
    driver: local
  rabbitmq-data:
    driver: local
networks:
  microservices-network:
    driver: bridge